kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: "10.244.0.0/16"
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry:5000"]
    endpoint = ["http://registry:5000"]
kubeadmConfigPatches:
- |
  kind: JoinConfiguration
  nodeRegistration:
    kubeletExtraArgs:
      "feature-gates": "CPUManager=true"
      "cpu-manager-policy": "static"
      "kube-reserved": "cpu=500m"
      "system-reserved": "cpu=500m"
nodes:
- role: control-plane
