FROM kubevirtci/base@sha256:850ac2e2828610b5f35f004f2a8a1ab23609a4c7891c8a1b68cbb7eef5f5dda0

ENV CENTOS_URL http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1905_01.Libvirt.box

RUN /download_box.sh ${CENTOS_URL}
