// Code generated by MockGen. DO NOT EDIT.
// Source: utils/ssh/ssh.go
//
// Generated by this command:
//
//	mockgen -source=utils/ssh/ssh.go -destination=utils/mock/mock_ssh.go -package=kubevirtcimocks
//

// Package kubevirtcimocks is a generated GoMock package.
package kubevirtcimocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSSHClient is a mock of SSHClient interface.
type MockSSHClient struct {
	ctrl     *gomock.Controller
	recorder *MockSSHClientMockRecorder
}

// MockSSHClientMockRecorder is the mock recorder for MockSSHClient.
type MockSSHClientMockRecorder struct {
	mock *MockSSHClient
}

// NewMockSSHClient creates a new mock instance.
func NewMockSSHClient(ctrl *gomock.Controller) *MockSSHClient {
	mock := &MockSSHClient{ctrl: ctrl}
	mock.recorder = &MockSSHClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSHClient) EXPECT() *MockSSHClientMockRecorder {
	return m.recorder
}

// Command mocks base method.
func (m *MockSSHClient) Command(cmd string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Command", cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Command indicates an expected call of Command.
func (mr *MockSSHClientMockRecorder) Command(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Command", reflect.TypeOf((*MockSSHClient)(nil).Command), cmd)
}
