apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: kube-public
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: CADATA
        server: https://192.168.66.110:6443
    contexts: null
    current-context: ""
    kind: Config
    preferences: {}
    users: null