---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: default
data:
  # Key value corresponds to a user name defined in ceph cluster
  admin: replace-me
  # Key value corresponds to a user name defined in ceph cluster
  # kubernetes: BASE64-ENCODED-PASSWORD
  # if monValueFromSecret is set to "monitors", uncomment the
  # following and set the mon there
  # monitors: BASE64-ENCODED-Comma-Delimited-Mons
