---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network
  namespace: default
spec:
  config: |
    {
      "cniVersion":"0.3.1",
      "name": "br10",
      "plugins": [
          {
              "type": "bridge",
              "bridge": "br10"
          }
      ]
    }
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: bridge-network
  name: test-multi-net
  namespace: default
spec:
  containers:
  - name: pod
    args:
    - sleep
    - "10000"
    image: quay.io/libpod/alpine:3.2
  terminationGracePeriodSeconds: 0
