FROM kubevirtci/base@sha256:840774a6731c52753dddafbcc69b51c25b891ec9622d4ee4ab73686b0c9dece1

ENV CENTOS_URL http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1802_01.Libvirt.box

RUN /download_box.sh ${CENTOS_URL}
